basePath: /api/v1
definitions:
  entity.Book:
    properties:
      author:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  request.BookCreate:
    properties:
      author:
        type: string
      title:
        type: string
    required:
    - author
    - title
    type: object
  request.BookUpdate:
    properties:
      author:
        type: string
      id:
        type: string
      title:
        type: string
    required:
    - author
    - id
    - title
    type: object
  response.ApiDataResponse:
    properties:
      data: {}
      success:
        type: boolean
    type: object
  response.ApiEmptyResponse:
    properties:
      success:
        type: boolean
    type: object
  response.ApiErrorDetail:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.ApiErrorResponse:
    properties:
      error:
        $ref: '#/definitions/response.ApiErrorDetail'
      success:
        type: boolean
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a Book Sharing API
  license:
    name: MIT
    url: https://mit-license.org/
  title: Book Sharing API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get list of books data
      parameters:
      - description: Item count per page
        in: query
        name: limit
        type: integer
      - description: List page number
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiDataResponse'
            - properties:
                data:
                  $ref: '#/definitions/entity.Book'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: List all book
      tags:
      - Book
    post:
      consumes:
      - application/json
      description: Input new book with title and author name
      parameters:
      - description: Request body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.BookCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiDataResponse'
            - properties:
                data:
                  $ref: '#/definitions/entity.Book'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: Create a new book
      tags:
      - Book
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Delete single book data
      parameters:
      - description: Book Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiEmptyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: Delete a book
      tags:
      - Book
    get:
      consumes:
      - application/json
      description: Get single book data
      parameters:
      - description: Book Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiDataResponse'
            - properties:
                data:
                  $ref: '#/definitions/entity.Book'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: Find a book
      tags:
      - Book
    put:
      consumes:
      - application/json
      description: Update existing book
      parameters:
      - description: Book Id
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.BookUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiDataResponse'
            - properties:
                data:
                  $ref: '#/definitions/entity.Book'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: Update a book
      tags:
      - Book
swagger: "2.0"
